---
title: "GNBF6010 seruat"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("C:/Users/may/Desktop/keti")
# save wanted RData in a file
# save(data, pbmc, all.genes, file = "my.RData")
# or save all data
# save.image(file="allData")
library(Seurat)
library(dplyr)
library(patchwork)
library("data.table")
library(scuttle)
library(ggplot2)
memory.limit(size=100000000)
# Load the RData
load("C:/Users/may/Desktop/keti/D3.RData")
```
Run non-linear dimensional reduction (UMAP/tSNE)
```{r}
pbmc <- RunTSNE(pbmc, dims = 1:6)
DimPlot(pbmc, reduction = "tsne")
```

Assigning cell type identity to clusters
```{r}
levels(pbmc)
new.cluster.ids <- c("Luminal", "Luminal","Luminal","T cell","Luminal","Endothelial","Luminal","Monocytic","Fibroblast","Luminal","Mast","Basal/Intermediate","Luminal","B cell","Chondrocyte","Endothelial")

pbmc@active.ident

names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
levels(pbmc)

# tSNE plot of annotated cell clusters
pbmc <- RunTSNE(pbmc, dims = 1:6)



png(file = "style.png")
DimPlot(pbmc, reduction = "tsne", label = TRUE)+ NoLegend() + scale_color_manual(values = c("#00DDA2","deeppink","goldenrod","purple","#33FF33","#00A9FF","red","yellow","gray"))
dev.off()
```


Endothelial cell
```{r}
rm(data)
rm(sce1)
sce4 = pbmc[, Idents(pbmc) %in% c( "Endothelial")]
sce4 <- NormalizeData(sce4, normalization.method = "LogNormalize", scale.factor = 1e4) 
sce4 <- FindVariableFeatures(sce4, selection.method = 'vst', nfeatures = 2000)
all.genes <- rownames(sce4)
sce4 <- ScaleData(sce4,features = all.genes)

sce4 <- RunPCA(sce4, features = VariableFeatures(object = sce4))

sce4 <- FindNeighbors(sce4, dims = 1:9)
sce4 <- FindClusters(sce4, resolution = 0.1)

sce4 <- RunTSNE(sce4, dims = 1:9)

png(file = "fib.png")
DimPlot(sce4, reduction = 'tsne')
dev.off()
#gene markers
FeaturePlot(sce4, features = c( "PECAM1","FLT1","PDPN","S100A4","THY1","ACTA2"))

#aEC
png(file = "fFI.png")
VlnPlot(sce4, features = c("S100A4","THY1","ACTA2"),pt.size=0)
dev.off()
```

Annotate Endothelial cells
```{r}
new.cluster.ids <- c("Endothelial","aEC","aEC","aEC","Endothelial","Endothelial")
names(new.cluster.ids) <- levels(sce4)
sce4 <- RenameIdents(sce4, new.cluster.ids)
sce4 <- RunTSNE(sce4, dims = 1:9)
DimPlot(sce4, reduction = "tsne", label = TRUE)
sce4@active.ident

sce4[["Annotation"]] <- sce4@active.ident
sce4@meta.data
```

Combine endothelial cell subgroups with fibroblasts
```{r}
pbmc.combined <- merge(pbmc[, Idents(pbmc) %in% c("Fibroblast")],y=sce4, project = "PBMC12K")
pbmc.combined[["Annotation"]]<- pbmc.combined@active.ident
pbmc.combined@meta.data
```

Cell communication by cellphoneDB
prepare files needed
```{r}
# create count.txt file
write.table(as.matrix(pbmc.combined@assays$RNA@data), 'sdata.txt', sep='\t', quote=F)

meta_data <- cbind(rownames(pbmc.combined@meta.data), pbmc.combined@meta.data[,'Annotation', drop=F])  
meta_data <- as.matrix(meta_data)
#create meta txt file
write.table(meta_data, 'smeta.txt', sep='\t', quote=F, row.names=F)
```






